<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>fiscal-futures-project-manual – My Manual for Fiscal Futures</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-991b1886d3c685c7aa2b62b80640c7af.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">My Manual for Fiscal Futures</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<ul>
<li>This document was created by Jahun Lee to better understand how the Fiscal Futures Project operates for himself as an RA without background in a financial management student and not familiar with the U.S. tax system.
<ul>
<li>The goal of this document is to provide all the information in one place.
<ul>
<li>Because it seems the information about the Fiscal Futures Project, particularly its methodology, is fragmented, at least for Jahun.</li>
</ul></li>
</ul></li>
</ul>
<hr>
<p>MoC</p>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
<ul>
<li>(Excerpt from <code>FF documentation.docs</code>)</li>
</ul>
<section id="the-structural-budget-gap" class="level6">
<h6 class="anchored" data-anchor-id="the-structural-budget-gap">The Structural Budget Gap</h6>
<ul>
<li>The Structural Budget Gap &gt;<span class="math display">\[예산 격차 = 총수입 – 총지출\]</span> &gt;&gt;격차가 0이면 예산은 균형이며, 곧 <strong>총수입 = 총지출</strong>입니다.<br>
&gt;&gt; 격차가 양(+)이면 <strong>흑자</strong>로, <strong>총수입 &gt; 총지출</strong>일 때 발생합니다.<br>
&gt;&gt; 격차가 음(–)이면 <strong>적자</strong>로, <strong>총수입 &lt; 총지출</strong>일 때 발생합니다.</li>
</ul>
<blockquote class="blockquote">
<p>일리노이 주 헌법(제8조 제2절) &gt; “재정연도에 대한 세출승인은 그 해에 이용 가능하다고 총회(General Assembly)가 추산한 자금을 초과할 수 없다.”</p>
</blockquote>
<ul>
<li><p>“이용 가능하다고 추산한 자금”</p>
<ul>
<li>세금과 수수료에서 발생할 것으로 예상되는 수입</li>
<li>기존 자산 잔액이나 새로운 차입</li>
</ul></li>
<li><p>과거 여러 해에 걸쳐 축적된 자산 잔액으로 현재 지출을 충당하거나, 향후 여러 해에 걸쳐 상환해야 할 새로운 부채를 떠안는 것과, 매년 발생하는 세금·수수료의 유입(흐름)으로 지출을 충당하는 것 사이에는 큰 차이가 있습니다.</p></li>
<li><p><strong>주의 근본적 재정 상태는 실제 지출과 실제 수입을 비교함으로써 더 잘 측정됩니다</strong></p>
<ul>
<li>주의 기초적인 재정 상태는 자산 잔액의 일회성 사용이나 신규 차입을 무시하고, 지출을 세금·수수료의 연간 유입과 비교함으로써 더 잘 측정됨</li>
<li>재정연도가 시작되기 전에 “이용 가능하다고 추산한 자금”에 의존하면, 실제 연말 수입이 장밋빛 전망치보다 훨씬 낮게 나타나더라도, 낙관적 수입 전망만으로 균형예산 요건을 충족할 수 있습니다.</li>
</ul></li>
<li><p>“총수입”을 “계정 잔액 및 신규 차입금 수입을 포함한 총 가용자금” 대신 사용함으로써, 이 지표는 지속가능한 수입에 초점을 맞추고 그 결과 기초적인 재정 상태를 반영합니다.</p></li>
<li><p>이 개념에 더 나은 명칭은 “구조적 예산 격차”일 수 있으며, 이는 지속가능한 수입과 비교한 주 지출 수준을 측정하거나 전망하려는 다른 연구들에서 사용하는 “구조적 적자” 개념과 맥을 같이합니다.</p></li>
</ul>
</section>
</section>
<section id="the-all-funds-budgets" class="level2">
<h2 class="anchored" data-anchor-id="the-all-funds-budgets">The All Funds Budgets</h2>
<section id="general-funds" class="level4">
<h4 class="anchored" data-anchor-id="general-funds">General Funds</h4>
<ul>
<li><strong>General Funds</strong> that reported by the State is not consistently defined over time.
<ul>
<li><p>It is difficult to obtain an accurate time series data of state revenue and expenditures.</p></li>
<li><p>In addition, it’s common for there to be within-year transfers between funds and cross-year reassignments of spending responsibility across funds.</p></li>
<li><p>일리노이 주 헌법은 “재정연도에 대한 세출승인은 그 해에 이용 가능하다고 총회가 추산한 자금을 초과할 수 없다”고 명시함. 그러나 일리노이 법은 “이용 가능한 자금”에 채무 발행, 일회성 수입원, 자산 매각 등을 포함할 수 있도록 허용함.</p>
<ul>
<li>예를 들어, 주가 톨 운영(toll booth operations)을 민간에 매각하는 경우, 해당 연도의 수입원으로 계상할 수 있습니다.</li>
</ul></li>
</ul></li>
</ul>
<p>감사원의 일부 보고는 “총 세출승인 및 비승인 기금(Total Appropriated and Non-Appropriated Funds)”을 다루지만, 이 지표에는 같은 해 여러 기금을 경유하는 수입의 이중계상이 일부 포함됩니다. - 또한, 승인(appropriated) vs 비승인(non-appropriated)의 구분은 해당 자원이나 지출이 진정한 주(州) 자원·기능인지 여부를 나타내지 않습니다. - 일부 경우에는, 특수기금(special funds)에서 승인 형태로 지출되지만, 그 기금 자체는 지방이 부과한 세금을 담고 있기도 합니다. - 또 일부 비승인 기금은 주가 부과한 세금을 보유합니다. - 주지사 운영예산(Governor’s Operating Budget)은 “모든 승인기금(All Appropriated Funds)”을 보고하지만, 동일한 한계가 적용됩니다.</p>
<ul>
<li>Illinois’ <strong>General Funds</strong>
<ul>
<li>the IOC and political and public discussion of the Illinois state budget, the concept of General Funds is used.</li>
<li>Illinois has 7 General Funds (at least since FY2022)
<ul>
<li>but over 700 funds in total (over 1,100 across the years in our database)</li>
<li><strong>7 General Funds in the State of Illinois system</strong>
<ul>
<li>General Revenue Fund (0001)</li>
<li>General Revenue–Common School Special Account Fund (0005)</li>
<li>Common School Fund (0412)</li>
<li>Education Assistance Fund (0007)</li>
<li>Fund for the Advancement of Education (0640)</li>
<li>Commitment to Human Services Fund (0644)</li>
<li>Budget Stabilization Fund (0686)</li>
</ul></li>
<li>일리노이는 대부분의 주와 달리 일반기금이 하나가 아니라 여러 개 있음
<ul>
<li>각 기금에는 특정 수입원이 있습니다.</li>
<li>교통 지출이 일반기금에서 집행되지 않음.</li>
</ul></li>
</ul></li>
</ul></li>
<li>Weakness of General Funds
<ul>
<li>일반기금 vs 전기금: 범주 수의 차이
<ul>
<li>일반기금으로 분석을 제한하면 교통 예산의 주요 부분, 부채 서비스, 지방정부로의 수입 이체, 연방기금으로 재원 조달되는 많은 프로그램 등 여러 중요한 수입·지출 범주가 제외됩니다.</li>
</ul></li>
<li>일반기금 구성요소의 변동성 증가
<ul>
<li>어떤 항목에 대한 주의 지불 방식이 해마다 변동되는 경우가 많아, 일반기금만 보면 연도 간 변화가 실제보다 더 크게 보일 수 있음
<ul>
<li>예컨대 어떤 연도에는 연방 프로그램 자금이 특정 주 특수기금에 예치되어 사용되다가, 다음 해에는 동일한 프로그램 지출이 일반기금에서 나오면, 지출 증가처럼 보이지만 실제로는 그렇지 않습니다.</li>
<li>반대로 일반기금에서 특수기금으로 재배정되면 지출 감소로 보이지만 실제로는 아닙니다.</li>
</ul></li>
</ul></li>
<li>일반기금 보고 총계에 포함된 비일반기금과의 이전(Transfer)
<ul>
<li>일반기금 수입에는 비일반기금으로부터의 유입이 포함되기도 하고, 일반기금 지출에는 비일반기금으로의 이전이 포함되기도 합니다.
<ul>
<li>이러한 이전의 포함 여부가 시간에 따라 달라지면 주 예산 상황 변화의 크기를 흐릴 수 있습니다.</li>
<li>더 포괄적인 예산 개념일수록 기금 간 이전분이 상계될 가능성이 큽니다.</li>
</ul></li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="all-funds" class="level4">
<h4 class="anchored" data-anchor-id="all-funds">All Funds</h4>
<ul>
<li>FF reports a more inclusive concept which called as “All Funds”.</li>
<li>To conduct meaningful analysis, FF reconstruct the entire set of Illinois revenue and expenditure categories in a consistent manner over time.
<ul>
<li>FF focuses on “sustainable revenue” by excluding new borrowing and other one-time revenue sources.</li>
</ul></li>
<li>FF’s All Funds measure includes funds that hold state resources, eliminates local resources, and corrects for inaccurate reporting practices (e.g., double-counting, fund-shifting, and year-to-year reporting changes)</li>
<li>FF argues that All Funds Model represents the total burdens and benefits of state government to taxpayers and residents.
<ul>
<li>For a detailed rationale of our choice to concentrate on All Funds versus General Funds see our “Why Ignore or half of the Illinois state budget picture? Consolidation of General and Special Fund Reporting,” (July 2011).<a href="#_ftn1">[1]</a></li>
</ul></li>
</ul>
</section>
</section>
<section id="전기금all-funds-예산에-개별-기금을-포함하는-기준" class="level2">
<h2 class="anchored" data-anchor-id="전기금all-funds-예산에-개별-기금을-포함하는-기준">전기금(All Funds) 예산에 개별 기금을 포함하는 기준</h2>
<p>앞서 전기금 개념이 시간에 따라 정의가 좁고 일관되지 못한 일반기금보다 주의 실제 재정 상황을 더 잘 보여준다고 설명했습니다. 다만 “전(全)”이라는 단어는 약간의 오해 소지가 있습니다. 일리노이의 700개+ 기금의 절대다수는 전기금 지표에 포함되지만, 일부는 그렇지 않습니다. 전기금 목록의 출발점은 모든 승인기금이지만, 아래 이유들로 소수의 승인기금을 제외하고, 여러 비승인 기금을 포함합니다.</p>
<section id="전기금-포함-여부를-판단하는-기준" class="level3">
<h3 class="anchored" data-anchor-id="전기금-포함-여부를-판단하는-기준">전기금 포함 여부를 판단하는 기준</h3>
<p><strong>기준 1: 그 기금이 주(州)가 부과하는 세금을 징수한다면 포함(INCLUDE).</strong><br>
주는 주세와 지방세(보통 지방선택적 판매·유틸리티세)를 모두 징수합니다. 주는 지방세를 징수해 지방정부에 환급합니다. 수납 시, 지방세 수입은 특정 지정 비승인 신탁기금에 예치됩니다. 주가 단순히 지방 과세기관의 징수 대행자 역할을 하는 경우, 해당 수납 신탁기금과 그 수입·지출은 분석 틀에 <strong>포함되지 않습니다</strong>. 반면 그 세금이 주를 위해 징수되는 경우, 기금과 그 수입은 <strong>포함됩니다</strong>. 개인소득세, 일반판매세, 기업소득에 대한 개인재산대체세(PPRT), 공공유틸리티, 유류세, 교통 갱신 기금에 대한 지방 몫에서 <strong>지방정부 이전(Local Government Transfers)</strong> 지출 범주를 구성합니다(코드의 “Local Transfers” 섹션).</p>
<p><strong>기준 2: 그 기금이 주 기능(state function)을 지원한다면 포함.</strong><br>
비승인 기금이라도 교육, 사회복지, 교통, 공공시설, 규제, 천연자원, 법집행 등 주 기능을 지원할 수 있습니다. 일반적으로 이는 특정 주 사업이나 목적을 위해 연방 자금을 보유하는 신탁기금입니다. 이 범주는 사실상 많은 승인된 주·연방 신탁기금 그룹과 동일합니다. 우리는 연방 자금을 수입으로 계상하므로, 승인기금은 포함하면서 본질적으로 동일한 기능을 하는 비승인 기금을 포함하지 않는 것은 일관적이지 않습니다.</p>
<p><strong>기준 3: 개인의 자금을 보유하는 기금이라면 제외(EXCLUDE).</strong><br>
개인의 돈을 보관하는 데 사용되는 기금이 있습니다. 대부분 비승인 기금이지만 일부는 승인 기금입니다. 제외 사례로는 자녀양육비 징수기금이나 직원 연금 본인부담 기금 등이 있습니다. 이러한 기금은 개인에게 속하는 돈을 보관하고 있으며 나중에 그 사람에게 반환되거나 그 사람을 위한 지불에 사용됩니다.</p>
<p><strong>기준 4: 그 기금의 지출 또는 수입이 다른 곳에서 이미 계상되었다면 제외(이중계상 방지).</strong><br>
일부 기금은 이미 다른 기금의 수입 또는 지출로 계상된 자금을 수납·지출합니다. 예컨대 Commercial Consolidation Fund는 개인·서비스 제공자·지방정부에 대한 주 급부 지급을 전자이체로 집행하는 대형 기금입니다. 이 기금으로의 <strong>유입</strong>은 계상되지만, 이 기금에서의 <strong>지급</strong>은 계상되지 않습니다.</p>
<p><strong>기준 5: 공적 기능이 아닌 특정 목적에 지정된 사용자 수수료를 보관하는 기금(도관·conduit)은 제외.</strong><br>
통상 우리는 공적 필수 기능이 아닌 특정 목적을 위해 지정된 사용자 수수료를 보관하는 비승인 기금을 제외합니다. 이러한 기금은 도관으로 간주될 수 있으며 틀에 포함하지 않았습니다. 예로, 주 박람회에서 마권경주 참가자에게서 수수료를 징수하여 경주 우승자에게 지급하는 Fund 0098을 제외합니다.</p>
<p><strong>기준 6: 대규모·중요한 주 기능을 지원하는 사용자 수수료 징수 기금이라면 포함(주 기능이 사용자 수수료 논리를 상회).</strong><br>
사용자 수수료로 지원되면서 <strong>주 기능</strong>(예: 교통)을 수행하는 비승인 기금은 틀에 포함합니다. 그 이유는, 설사 사용자 수수료와 기금 구조가 없더라도 주 기능은 수행되어야 하기 때문입니다. 가장 큰 예는 일리노이 주 유료도로 수입기금(Illinois State Toll Highway Revenue Fund)으로, 통행료를 징수하여 일리노이 유료도로의 확장 및 유지보수를 지원합니다.</p>
</section>
</section>
<section id="전기금-데이터베이스의-데이터-출처" class="level2">
<h2 class="anchored" data-anchor-id="전기금-데이터베이스의-데이터-출처">전기금 데이터베이스의 데이터 출처</h2>
<ul>
<li>FF’s All Funds database comes from the Illinois Comptroller’s Office (IOC).
<ul>
<li>Currently the database includes 300,000 individual records for fiscal years 1998 to 2022</li>
</ul></li>
<li>Fiscal Futures 전기금 데이터베이스의 정보는 일리노이 감사원에서 제공한 상세 자료에 기반합니다. 현재 데이터베이스에는 1998~2022 회계연도에 대한 30만 개의 개별 기록이 포함되어 있습니다.</li>
</ul>
<p><strong>지출 데이터.</strong> - 각 지출 기록에 포함된 주요 정보는 회계연도, 기금, 기관, 객체(object), 세출승인입니다. - 지출을 범주로 집계하는 핵심 기준(아래 설명)은 해당 지출에 책임이 있는 주 정부 기관입니다. - 현재 데이터셋에는 129개의 개별 기관이 있습니다. - 다음 절에서는 이를 연도 전체에 걸쳐 포괄적이며 일관되게 정의된 더 적은 수의 범주로 축약하는 방법을 다룹니다. - 재코딩 과정에 대한 세부사항은 R 코드 전반의 주석을 참고하십시오.</p>
<p><strong>수입 데이터.</strong> - 각 수입 기록에 포함된 주요 정보는 회계연도, 기금, 기관, 수입원(source)입니다. - 감사원 웹사이트의 정보를 사용하여 2,137개의 상세 수입원 코드를 33개의 더 넓은 수입 유형 코드로 통합하며, 그 목록은 다음 절에 제시되어 있습니다. - 재코딩 과정의 세부는 R 코드의 주석을 참고하십시오.</p>
<p><del>아래에는 Fiscal Futures Project 전기금 예산의 각 지출 및 수입 범주가 나열되어 있습니다. 각 항목에는 보다 설명적인 제목 버전 또는 포함된 주요 구성 기관이나 수입원 목록이 포함됩니다. 설명과 목록은 포괄적이지 않으며, 많은 소규모 구성요소는 포함하지 않습니다.</del></p>
</section>
<section id="source-of-data-for-all-funds-database" class="level2">
<h2 class="anchored" data-anchor-id="source-of-data-for-all-funds-database">Source of Data for All Funds Database</h2>
<ul>
<li>Information for the FF All Funds database comes from the IOC.
<ul>
<li>Currently the database includes ==300,000== individual records for FY 1998 - ==2022==</li>
</ul></li>
<li>Expenditure data
<ul>
<li>The principal information included in each spending record is <strong><em>fiscal year, fund, agency, object, and appropriation</em></strong></li>
<li>The key measure to aggregate spending into categories is the state <strong><em>agency</em></strong> responsible for the expenditure.</li>
<li>==Link to R code==</li>
</ul></li>
<li>Revenue data
<ul>
<li>the principal information included in each revenue record is <strong><em>fiscal year, fund, agency, and source</em></strong>.</li>
<li>Information from the Comptroller’s website is used to collapse the 2,137 detailed <strong><em>source</em></strong> codes into 33 broader revenue <strong><em>type</em></strong> codes.</li>
<li>==Link to R code==</li>
</ul></li>
</ul>
<section id="expenditure-categories" class="level3">
<h3 class="anchored" data-anchor-id="expenditure-categories">Expenditure Categories</h3>
<ul>
<li>대부분의 경우, 지출 범주는 고유한 그룹 코드(agency code와 대응됨)가 부여된 주(州)의 “부서(department),” “지부(branch),” “기관(agency),” “위원회(board),” 또는 “위원회(commission)”와 같음.</li>
<li>일부 중요한 예산 범주들은 여러 부서나 기관의 운영 예산 일부로 보고되지만, 별도의 분석이 필요함
<ul>
<li>quasi-agencies
<ul>
<li>연금, 부채 상환, 주(州) 공무원 의료보험, 메디케이드, 지방정부로의 수입 이전에 대한 지출</li>
</ul></li>
<li>고유 기관 코드를 가진 지출 범주</li>
<li>여러 소규모 기관들의 통합</li>
</ul></li>
</ul>
<section id="quasi-agencies" class="level5">
<h5 class="anchored" data-anchor-id="quasi-agencies">Quasi-Agencies</h5>
<pre><code>- the following categories are separated from other agency budgets
    - 901. Pension Contributions
    - 903. Debt Service
    - 904. State Employee Health Care
    - 945. Medicaid
    - 970. Transfer of Revenue to Local Governments</code></pre>
<ul>
<li><strong>901. Pension Contributions</strong> (<em>Not used for FY2024 onward. Pension expenditures stay in their.</em>)
<ul>
<li><p><strong>Fiscal Futures only includes the state’s payments into the pension funds and employer contributions as “pension expenditures.”</strong></p></li>
<li><p>State payments to the following pension systems:</p>
<ul>
<li>593.&nbsp; Teachers Retirement System (TRS)</li>
<li>589.&nbsp; State Employee Retirement System (SERS)</li>
<li>693.&nbsp; State University Retirement System (SURS)</li>
<li>275.&nbsp; Judges Retirement System (JRS)</li>
<li>131.&nbsp; General Assembly Retirement System (GARS)</li>
</ul></li>
<li><p><strong>Object = 4430</strong>, - <strong>Funds 0473, 0477, 0479, 0481, (TRS, JRS, SERS, GARS),</strong> - <strong>Funds 0755, 0786, 0787, 0788, 0789 (deferred compensation plan, GAR excess benefit, JRS excess benefit, SER excess benefit, TRS excess benefit),</strong> - are all funds that cover appropriations for benefit payments, pension income, and annuities to employees that worked for the State. - All of the expenditures from these funds were set to in_ff =0 and therefore <strong>NOT included</strong> in aggregate pension expenditures in the analysis.</p></li>
<li><p><strong>Fund 0825 is</strong> for the pension obligation acceleration bond and is also <strong>excluded</strong> from the analysis.</p>
<ul>
<li>&nbsp;<strong>Object = 4431</strong> is for state payments <strong>into</strong> pensions and <strong>is included</strong> in the analysis**.&nbsp;</li>
</ul></li>
<li><p><strong>Object 1160-1165</strong> are employer contributions (mostly SERS) and also <strong>included</strong>.</p></li>
<li><p><strong>Agencies 131, 275, 586, 589, 593, 594, 693</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 34%">
<col style="width: 25%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Pensions Separated<br>FY2020?-2023</th>
<th>Pension Expenditures left in Agency Groups<br>FY 2024 +</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>593 &amp; 594. Teachers Retirement System (TRS)</td>
<td>901. State Pension Contribution</td>
<td>959. K-12 Education</td>
</tr>
<tr class="even">
<td>589. State Employee Retirement System (SERS)</td>
<td>901. State Pension Contribution</td>
<td>948. Other Departments</td>
</tr>
<tr class="odd">
<td>693. State University Retirement System (SURS)</td>
<td>901. State Pension Contribution</td>
<td>960. Higher Education</td>
</tr>
<tr class="even">
<td>275. Judges Retirement System (JRS)</td>
<td>901. State Pension Contribution</td>
<td>920. Judicial</td>
</tr>
<tr class="odd">
<td>131. General Assembly Retirement System (GARS)</td>
<td>901. State Pension Contribution</td>
<td>910. Legislative</td>
</tr>
</tbody>
</table></li>
</ul></li>
<li><strong>903. Debt Service.</strong>&nbsp;
<ul>
<li>Interest payments on both short-term and long-term debt.&nbsp;</li>
<li><strong>We do not include escrow payments or principal payments.</strong>
<ul>
<li>Bond proceeds are not a sustainable revenue source and principal payments are not considered a cost for short term borrowing and general obligation bonds.</li>
<li>There has been discussion on including general obligation debt service principal payments as an expenditure based on capital budgeting theory of debt being a proxy for capital depreciation.</li>
<li>However if principal payments are included, then they are being counted twice: Once as the spending category that the money was spent on and again as “debt service” payments later.</li>
</ul></li>
<li>However, overall debt (new and paid back) should be tracked and commented on separately.</li>
<li>Excludes Tollway Debt (principal and interest payments are combined in one observation).
<ul>
<li>It is possible to look at the principal to interest ratio for capital debt and estimate the principal &amp; interest ratio for the tollway if we wanted to do that.</li>
</ul></li>
</ul></li>
<li><strong>904. State Employee Health Care.</strong>&nbsp;
<ul>
<li><p>Sum of expenditures for “health care coverage as elected by members per state employees group insurance act.”&nbsp;</p></li>
<li><p>The payments are made from the Health Insurance Reserve Fund.&nbsp;</p></li>
<li><p>We subtract the share that came from employee contributions to create a net healthcare cost for the state and exclude the employer group contributions to avoid double counting the costs (employer group contributions &amp; provision of healthcare costs are both included in the expenditure data).</p></li>
<li><p><em>turns specific items into State Employee Healthcare (agency=904)</em> ```r code fund==“0907” &amp; (agency==“416” &amp; appr_org==“20”) ~ “904”, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;# central management Bureau of benefits using health insurance reserve_</p>
<p>fund==“0907” &amp; (agency==“478” &amp; appr_org==“80”) ~ “904”, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;# agency = 478: healthcare &amp; family services using health insurance reserve - stopped using this in 2012_</p>
<p>TRUE ~ as.character(agency))) ```</p></li>
</ul></li>
<li><strong>945. Medicaid.</strong>&nbsp;
<ul>
<li>That sum of the Healthcare and Family Services (or Public Aid in earlier years, <em>agency</em> code 478) expenditures for Medical (<em>appr_organization</em> code 65) with awards and grants (<em>object</em> codes 4400 and 4900).&nbsp;</li>
<li>Medicaid as a spending category includes healthcare provider support funds for services.</li>
<li>For FY 2021 and FY 2022, State CURE dollars (fund == “0324”) were included in the Medicaid spending category due to sharing the fund number, appr_organization, and object codes with other federally supported healthcare expenditures.</li>
</ul></li>
<li><strong>970. Transfer of Revenue to Local Governments.</strong>&nbsp;
<ul>
<li>The share of certain taxes levied state-wide at a common rate and then transferred to local governments.&nbsp;
<ul>
<li>(Purely local-option taxes levied by specific local governments with the state acting as collection agent are <em>not</em> included in the model).</li>
</ul></li>
<li>The five corresponding revenue-source items are:
<ul>
<li>02.&nbsp; Local share of Personal Income Tax</li>
<li>03.&nbsp; Personal Property Replacement Tax on Business Income</li>
<li>06.&nbsp; Local share of General Sales Tax</li>
<li>09.&nbsp; Local share of Motor Fuel Tax &amp; Transportation Renewal Fund</li>
<li>12.&nbsp; Personal Property Replacement Tax on Public Utilities</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="single-agencies-that-function-as-expenditure-categories." class="level5">
<h5 class="anchored" data-anchor-id="single-agencies-that-function-as-expenditure-categories.">Single agencies that function as expenditure categories.&nbsp;</h5>
<pre><code>- After removal of items described above.&nbsp;</code></pre>
<ul>
<li>4<strong>02.&nbsp; Aging</strong>, Department of</li>
<li><strong>406.&nbsp; Agriculture</strong>, Department of (includes: 538. Farm Development Authority; 556 Rural Bond Bank – old agencies)</li>
<li><strong>418.&nbsp; Children and Family Services</strong>, Department of</li>
<li><strong>420.&nbsp; Commerce and Economic Opportunity,</strong> Department of</li>
<li><strong>422.&nbsp; Natural Resources</strong>, Department of</li>
<li><strong>425. Juvenile Justice,</strong> Department of</li>
<li><strong>426.&nbsp; Corrections</strong>, Department of</li>
<li><strong>427.&nbsp; Employment Security</strong>, Department of</li>
<li><strong>444.&nbsp; Human Services</strong>, Department of</li>
<li><strong>478.&nbsp; Healthcare &amp; Family Services</strong>, Department of (net of 945. Medicaid)</li>
<li><strong>482.&nbsp; Public Health</strong>, Department of</li>
<li><strong>492.&nbsp; Revenue</strong>, Department of</li>
<li><strong>494.&nbsp; Transportation</strong> (net Local Share)– e.g.&nbsp;public transportation, railroads, construction, equipment, maintenance</li>
<li><strong>532.&nbsp; Environmental Protect Agency</strong> – e.g.&nbsp;Air pollution control, land pollution control, clean water programs, stormwater management.</li>
<li><strong>557.&nbsp; Illinois State Toll Highway Authority</strong> – e.g.&nbsp;&nbsp;tollway capital Improvement, maintenance. Principal and interest are included as Tollway expenditures since they are combined in the data.</li>
<li><strong>684.&nbsp; Illinois Community College Board</strong></li>
<li><strong>691.&nbsp; Illinois Student Assistance Commission</strong> ###### Combination of multiple smaller agencies.&nbsp;</li>
<li><strong>970. Central Services</strong>
<ul>
<li>416.&nbsp; Central Management Services</li>
<li><ol start="448" type="1">
<li>Innovation and Technology</li>
</ol></li>
</ul></li>
<li><strong>910. Legislative</strong>.&nbsp; Combination of
<ul>
<li><p>101.&nbsp; General Assembly</p></li>
<li><p>102.&nbsp; Office of the Legislative Inspector General</p></li>
<li><p>103.&nbsp; Office of the Auditor General</p></li>
<li><p>105.&nbsp; Commission on Government Forecasting &amp; Accountability (COGFA)</p></li>
<li><p>108.&nbsp; Legislative Information System</p></li>
<li><p>109.&nbsp; Legislative Audit Commission</p></li>
<li><p>110.&nbsp; Legislative Printing Unit</p></li>
<li><p>115.&nbsp; Legislative Reference Bureau</p></li>
<li><p>120.&nbsp; Legislative Ethics Commission</p></li>
<li><p>156.&nbsp; Office of the Architect of the Capitol</p></li>
<li><p>167.&nbsp; Joint Committee on Administrative Rules</p></li>
<li><p><em>Past Legislative:</em> &nbsp;- <em>107. Commission on Intergovernmental Cooperation</em></p>
<ul>
<li><em>112.&nbsp; Legislative Research Unit</em></li>
<li><em>155.&nbsp; Legislative Space Needs Commission</em></li>
<li><em>140.&nbsp; Pension Laws Commission</em></li>
</ul></li>
</ul></li>
<li><strong>920.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Judicial</strong>.&nbsp; Combination of
<ul>
<li>201.&nbsp; Supreme Court</li>
<li>210.&nbsp; Supreme Court Historic Preservation Commission</li>
<li><ol start="280" type="1">
<li>Courts Commission</li>
</ol></li>
<li>285.&nbsp; Judicial Inquiry Board</li>
<li>290.&nbsp; State Appellate Defenders Office</li>
<li>295.&nbsp; State’s Attorneys Appellate Prosecutor</li>
<li>528.&nbsp; Court of Claims &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- &nbsp; <em>Past agencies:</em></li>
<li><em>202.&nbsp; Attorney Registration and Disciplinary Commission</em></li>
<li><em>203.&nbsp; Board of Admissions to the Bar</em></li>
<li><em>205.&nbsp; Clerk of the Supreme Court</em></li>
<li><em>215.&nbsp; Appellate Court District 1</em></li>
<li><em>225.&nbsp; Appellate Court District 2</em></li>
<li><em>235.&nbsp; Appellate Court District 3</em></li>
<li><em>245.&nbsp; Appellate Court District 4</em></li>
<li><em>255.&nbsp; Appellate Court District 5</em></li>
</ul></li>
<li><strong>930.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Elected Officers</strong>.&nbsp; Combination of
<ul>
<li>310.&nbsp; Governor</li>
<li>330.&nbsp; Office of the Lt. Governor</li>
<li>340.&nbsp; Office of the Attorney General</li>
<li>350.&nbsp; Secretary of State</li>
<li>360.&nbsp; Illinois Office of the Comptroller</li>
<li>370.&nbsp; State Treasurer’s Office</li>
</ul></li>
<li><strong>941.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Public Safety</strong>.&nbsp; Combination of
<ul>
<li>425.&nbsp; Department of Juvenile Justice</li>
<li>466.&nbsp; Military Affairs</li>
<li>493.&nbsp; Department of State Police</li>
<li>546.&nbsp; Illinois Criminal Justice Information Authority</li>
<li>569.&nbsp; Law Enforcement Training and Standards Board</li>
<li>578.&nbsp; Prisoner Review Board</li>
<li>583.&nbsp; Sex Offender Management Board</li>
<li>588.&nbsp; Illinois Emergency Management Agency</li>
<li>591.&nbsp; Illinois State Police Merit Board</li>
<li>592.&nbsp; Office of the State Fire Marshal</li>
</ul></li>
<li><strong>944.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Business &amp; Professional Regulation</strong>.&nbsp; Combination of
<ul>
<li>440.&nbsp; Department of Financial and Professional Regulation</li>
<li>446.&nbsp; Department of Insurance</li>
<li>524.&nbsp; Illinois Commerce Commission</li>
<li>563.&nbsp; Illinois Workers’ Compensation Commission</li>
</ul></li>
<li><strong>946.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Capital Improvement</strong>.&nbsp; Combination of
<ul>
<li>511.&nbsp; Capital Development Board 554.&nbsp; Illinois Sports Facilities Authority 574.&nbsp; Metropolitan Fair and Exposition Authority 598.&nbsp; Upper Illinois River Valley Development Authority</li>
</ul></li>
<li><strong>948.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Other Departments</strong>.&nbsp; Combination of 442.&nbsp; Department of Human Rights 445.&nbsp; IL Power Agency 452.&nbsp; Department of Labor 458.&nbsp; Illinois Lottery 497.&nbsp; Department of Veterans Affairs 507.&nbsp; Governor’s Office of Management and Budget
<ul>
<li><strong><em>Non-pension items from pension departments</em></strong>
<ul>
<li><ol start="131" type="1">
<li>General Assembly Retirement System</li>
</ol></li>
<li><ol start="275" type="1">
<li>Judges Retirement System</li>
</ol></li>
<li><ol start="589" type="1">
<li>State Employees’ Retirement System</li>
</ol></li>
<li><ol start="593" type="1">
<li>Teachers’ Retirement System</li>
</ol></li>
<li><ol start="594" type="1">
<li>Teachers’ pension and retirement system</li>
</ol></li>
<li><ol start="693" type="1">
<li>State University Retirement System</li>
</ol></li>
</ul></li>
</ul></li>
<li><strong>949.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Other Boards &amp; Commissions</strong>.&nbsp; Combination of 503.&nbsp; Illinois Arts Council 509.&nbsp; Office of the Executive Inspector General 510.&nbsp; Executive Ethics Commission 517.&nbsp; Illinois Civil Service Commission 526.&nbsp; Deaf and Hard of Hearing Commission 527.&nbsp; Comprehensive Health Insurance Board 529.&nbsp; East St.&nbsp;Louis Financial Advisory Authority
<ol type="1">
<li>Committee on Equity and Inclusion 534.&nbsp; Health Information Exchange Authority 537.&nbsp; Guardianship and Advocacy Commission 540.&nbsp; Illinois Health Care 541.&nbsp; Historic Preservation Agency 542.&nbsp; Human Rights Commission 548.&nbsp; Illinois Education Labor Relations Board 555.&nbsp; Illinois State Board of Investments 558.&nbsp; Illinois Council on Developmental Disabilities 559.&nbsp; Illinois Violence Prevention Authority 562.&nbsp; Procurement Policy Board 564.&nbsp; Illinois Independent Tax Tribunal 565.&nbsp; Illinois Gaming Board 567.&nbsp; Liquor Control Commission 571.&nbsp; Medical Center Commission 575.&nbsp; Prairie State 2000 Authority 579.&nbsp; Illinois Racing Board 580.&nbsp; Property Tax Appeal Board 587.&nbsp; Illinois State Board of Elections 590.&nbsp; Illinois Labor Relations Board &nbsp;&nbsp;&nbsp;- &nbsp;&nbsp;&nbsp; <em>Past Boards &amp; Commissions:</em>
<ul>
<li><em>525. Drycleaner Commission</em></li>
<li><em>568. IL Charter Schools Commission</em></li>
<li><em>585. Southwestern Development Authority</em></li>
</ul></li>
</ol></li>
<li><strong>959. K-12 Education</strong> - eg. After school programs, charter schools, breakfast/lunch programs, commodities, etc.
<ul>
<li>586.&nbsp; Illinois State Board of Education (net of special education funds to 945. Medicaid).</li>
</ul></li>
<li><strong>960. University Education.</strong> &nbsp;State contributions to higher education.&nbsp; Note this does not include the entire budget of the schools, only the amount they get from the state. 601.&nbsp; Board of Higher Education 608.&nbsp; Chicago State University 612.&nbsp; Eastern Illinois University 616.&nbsp; Governors State University 620.&nbsp; Northeastern Illinois University 628.&nbsp; Western Illinois University 636.&nbsp; Illinois State University 644.&nbsp; Northern Illinois University 664.&nbsp; Southern Illinois University 676.&nbsp; University of Illinois 692.&nbsp; Illinois Math and Science Academy 695.&nbsp; State Universities Civil Service Merit Board</li>
</ul>
</section>
</section>
</section>
<section id="methodology" class="level1">
<h1>Methodology</h1>
<section id="brief-history-of-the-project" class="level4">
<h4 class="anchored" data-anchor-id="brief-history-of-the-project">Brief History of the Project</h4>
<ul>
<li>2016년 이전에는 일부 집계된 데이터가 감사원(Comptroller) 웹사이트와 그들의 『상세 연간보고서』 PDF 파일에서 수작업으로 수집되었습니다.</li>
<li>2022년에는 모델을 구동하던 Stata 코드를 R로 재코딩하여 공개했습니다.</li>
</ul>
</section>
<section id="files" class="level2">
<h2 class="anchored" data-anchor-id="files">Files</h2>
<section id="raw-files" class="level6">
<h6 class="anchored" data-anchor-id="raw-files">Raw Files</h6>
<ul>
<li><code>allrevfiles</code> : raw data from IOC</li>
<li><code>allexpfiles</code> : raw data from IOC</li>
</ul>
<blockquote class="blockquote">
<p>These files are not reflected the changed names of funds and agencies. - variable names might be modified for consistency ###### Processed Files - <a href="#%5Efd7c78">funds_ab_in.xlsx</a> -</p>
</blockquote>
</section>
<section id="funds_ab_in.xlsx" class="level3">
<h3 class="anchored" data-anchor-id="funds_ab_in.xlsx">funds_ab_in.xlsx</h3>
<p>^fd7c78</p>
<ul>
<li><p>1998년 이후 존재한 모든 기금, 현재 존속 여부, 다양한 목적을 위해 번호가 재사용되었는지 여부, 그리고 IOC가 매년 사용하는 신규 기금 번호가 담겨 있음</p></li>
<li><p>new or reused funds</p></li>
<li><p>reused funds</p>
<ul>
<li>한 번 재사용된 기금은 첫 자릿수 0을 9로 바꿔 표기한다.
<ul>
<li>예: <code>0350</code> → <code>9350</code> (용도 변경)</li>
</ul></li>
<li>두 번 재사용되면 앞 두 자리를 10으로 바꾼다.
<ul>
<li>예: <code>0367</code> → <code>10367</code> (두 차례 용도 변경: 0367 → 9367 → 10367)</li>
</ul></li>
</ul></li>
<li><p>엑셀 파일에는 대안 표기(예: <code>0397-A</code>, <code>0397-B</code>)와 기금 사용이 중단된 연도 변수도 포함됨</p></li>
</ul>
</section>
<section id="rev_allyears.csv" class="level3">
<h3 class="anchored" data-anchor-id="rev_allyears.csv">rev_allyears.csv</h3>
<ul>
<li><ul>
<li>수입 집계를 위해서 <code>rev_allyears</code> 파일에 <code>funds_ab_in</code>을 조인하고, 이어서 <code>ioc_source_type</code> 파일을 조인함
<ul>
<li><strong>매년</strong> <code>funds_ab_in</code>, <code>ioc_source_type</code>를 업데이트해야 한다!</li>
</ul></li>
</ul></li>
<li><h3 id="rev_temp.csv-exp_temp.csv" class="anchored"><code>rev_temp.csv</code>, <code>exp_temp.csv</code></h3></li>
<li><p>초기 결합본은 <code>exp_allyears</code>, <code>rev_allyears</code> 데이터프레임으로 저장된다.</p></li>
<li><p>이후 변수 재코딩을 거치며 각각 <code>exp_temp</code>, <code>rev_temp</code>로 저장한다.</p></li>
<li><p>이는 Fiscal Gap 범주 그룹 생성 및 추가 정제(“Calculating the Fiscal Gap” 페이지에서 수행) <strong>이전 단계</strong>이다.</p></li>
<li><p><code>exp_temp.csv</code>와 <code>rev_temp.csv</code>는 비(非) Fiscal Futures 연구자들이 자체 분석에 사용하기에 가장 적합한 자료일 가능성이 큼</p>
<ul>
<li>이 파일들은 1998년부터 현재까지의 기관과 기금을 일관되게 추적하도록 정리되어 있음</li>
</ul></li>
</ul>
<p><code>exp_temp</code>, <code>rev_temp</code>(중간산출물)</p>
</section>
</section>
<section id="categorization" class="level2">
<h2 class="anchored" data-anchor-id="categorization">Categorization</h2>
<section id="tax-refunds" class="level3">
<h3 class="anchored" data-anchor-id="tax-refunds">Tax refunds</h3>
<ul>
<li>세금 환급(tax refunds)을 지출에서 제외하고 수입에서 차감(음수 수입) 처리</li>
</ul>
</section>
<section id="expenditure" class="level3">
<h3 class="anchored" data-anchor-id="expenditure">Expenditure</h3>
<ul>
<li><p><strong>연금/그룹코딩</strong> 규칙으로 지출을 정책적 기능 그룹에 재분류</p></li>
<li><p><strong>연방→주 이전(57/58/59)</strong>을 재분류</p></li>
<li><p>일회성/비지속 수입(코로나 CURE 등) 플래그·제외</p></li>
<li><p><strong>전처리 후 집계</strong>(wide→labeling→long)로 연도별 수입/지출/갭 표와 그래프 준비</p>
<p>mutate(Category_name = case_when( Category == “02” ~ “INDIVIDUAL INCOME TAXES” , Category == “03” ~ “CORPORATE INCOME TAXES” , Category == “06” ~ “SALES TAXES” , Category == “09” ~ “MOTOR FUEL TAX” , Category == “12” ~ “PUBLIC UTILITY TAXES” , Category == “15” ~ “CIGARETTE TAXES” , Category == “18” ~ “LIQUOR GALLONAGE TAXES” , Category == “21” ~ “INHERITANCE TAX” , Category == “24” ~ “INSURANCE TAXES&amp;FEES&amp;LICENSES” , Category == “27” ~ “CORP FRANCHISE TAXES &amp; FEES” , Category == “30” ~ “HORSE RACING TAXES &amp; FEES”, # in Other Category == “31” ~ “MEDICAL PROVIDER ASSESSMENTS” , Category == “32” ~ “GARNISHMENT-LEVIES” , # dropped Category == “33” ~ “LOTTERY RECEIPTS” , Category == “35” ~ “OTHER TAXES” , Category == “36” ~ “RECEIPTS FROM REVENUE PRODUCING”, Category == “39” ~ “LICENSES, FEES &amp; REGISTRATIONS” , Category == “42” ~ “MOTOR VEHICLE AND OPERATORS” , Category == “45” ~ “STUDENT FEES-UNIVERSITIES”, # dropped Category == “48” ~ “RIVERBOAT WAGERING TAXES” , Category == “51” ~ “RETIREMENT CONTRIBUTIONS” , # dropped Category == “54” ~ “GIFTS AND BEQUESTS”, Category == “57” ~ “FEDERAL OTHER” , Category == “58” ~ “FEDERAL MEDICAID”, Category == “59” ~ “FEDERAL TRANSPORTATION” , Category == “60” ~ “OTHER GRANTS AND CONTRACTS”, #other Category == “63” ~ “INVESTMENT INCOME”, # other Category == “66” ~ “PROCEEDS,INVESTMENT MATURITIES” , #dropped Category == “72” ~ “BOND ISSUE PROCEEDS”, #dropped Category == “75” ~ “INTER-AGENCY RECEIPTS”, #dropped Category == “76” ~ “TRANSFER IN FROM OUT FUNDS”, #other Category == “78” ~ “ALL OTHER SOURCES” , Category == “79” ~ “COOK COUNTY IGT”, #dropped Category == “98” ~ “PRIOR YEAR REFUNDS”, #dropped T ~ “Check Me!”</p></li>
</ul>
</section>
</section>
</section>
<section id="diagram" class="level1">
<h1>Diagram</h1>
<pre class="mermaid"><code>flowchart TB
    A[**FOIA Request**
     Get raw Excel files] --&gt; B[**&amp;Check new &amp; reused agencies/funds**]
    B --&gt; C[**Update funds_ab_in.xlsx** 
          include/exclude funds]
    C --&gt; D[**Rename variables for consistency**]
    D --&gt; E[**Combine past + current year files**]
    E --&gt; F[**Recode reused funds/agencies**]
    F --&gt; G[**Create exp_temp &amp; rev_temp**]
    G --&gt; H[Export CSVs for Fiscal Gap analysis]</code></pre>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/jahunlee\.github\.io\/Fiscal-Futures");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>